import os
import unittest
import datetime

from idmtools.assets import AssetCollection
from idmtools.core.platform_factory import Platform
from idmtools_models.python.json_python_task import JSONConfiguredPythonTask

from idmtools_calibra.algorithms.optim_tool import OptimTool
from idmtools_calibra.calib_manager import CalibManager
from idmtools_calibra.plotters.likelihood_plotter import LikelihoodPlotter
from idmtools_calibra.plotters.site_data_plotter import SiteDataPlotter
from idmtools_calibra.process_state import StatusPoint
from idmtools_calibra.rmse_site import RMSESite
from tests.unittests import params

CURRENT_DIRECTORY = os.path.dirname(__file__)


class TestCalibraManager(unittest.TestCase):

    def setUp(self) -> None:
        def map_sample_to_model_input(simulation, sample):
            """
            This method maps the samples generated by the next point algorithm to the model inputs (via the simulation object).
            All parameters specified for dynamic calibration (above) that do not have a MapTo value must have associated mapping
                logic in this method.
            Args:
                simulation: idmtools simulation
                sample: The sample containing a values for all the params. e.g. {'Clinical Fever Threshold High':1, ... }

            Returns: A dictionary containing the tags that will be attached to the simulation
            """

            tags = {}
            from functools import partial
            for p in params.CALIBRATION_PARAMETERS:
                if "MapTo" not in p:
                    raise Exception(
                        "Calibration parameter dicts must include a MapTo (model param name) entry. Missing from parameter: %s"
                        % p["Name"]
                    )
                if p["Name"] not in sample:
                    print(
                        "Warning: %s not in sample, perhaps resuming previous iteration"
                        % p["Name"]
                    )
                    continue
                value = sample.pop(p["Name"])
                mapto_key = p["MapTo"]
                tags.update(simulation.task.set_parameter(mapto_key.replace("config:", ""), value))

            for name, value in sample.items():
                print("UNUSED PARAMETER:" + name)
            assert len(sample) == 0  # All params used
            return tags

        site = RMSESite(
            name='rmse_site',
            reference_sources={
                'production': os.path.join('..', '..', 'examples', 'solar', 'reference', 'production.csv')}
        )
        self.n_samples = 5
        self.max_iterations = 2
        optimtool = OptimTool(params.CALIBRATION_PARAMETERS, samples_per_iteration=self.n_samples)
        plotters = [LikelihoodPlotter(True), SiteDataPlotter(True)]
        assets = AssetCollection()
        assets.add_directory(os.path.join('..', '..', 'examples', 'solar', 'bin'), relative_path="bin")
        task = JSONConfiguredPythonTask(
            script_path=str(os.path.join('..', '..', 'examples', 'solar', 'bin', 'linear_model.py')),
            common_assets=assets,
            config_file_name='config.json')
        calib_manager = CalibManager(
            name='test_dummy_calibration',
            task=task,
            map_sample_to_model_input_fn=map_sample_to_model_input,
            sites=[site],
            next_point=optimtool,
            sim_runs_per_param_set=1,
            max_iterations=self.max_iterations,
            plotters=plotters)
        platform = Platform("SlurmStage")
        calib_manager.platform = platform
        # calib_manager.run_calibration(directory=directory)
        self.calib_manager = calib_manager

    def test_dummy_calibra_manager_resume(self):
        uniq_filename = str(datetime.datetime.now().date()) + '_' + str(datetime.datetime.now().time()).replace(':',
                                                                                                                '_')
        directory = os.path.join(CURRENT_DIRECTORY, "calibra_result", uniq_filename)
        self.calib_manager.run_calibration(directory=directory)
        self.assertEqual(self.calib_manager.current_iteration.iteration, 1)
        self.assertEqual(self.calib_manager.all_results.shape[0], self.n_samples * self.max_iterations)  # 2*(5sim/iter) iterations
        suite_id = str(self.calib_manager.suite_id)
        self.calib_manager.run_calibration(directory=directory, resume=True, iteration=0, iter_step='commission',
                                           loop=False)
        self.assertEqual(self.calib_manager.current_iteration.iteration, 0)
        self.assertEqual(self.calib_manager.all_results.shape[0],
                         self.n_samples)  # rerun only return first iteration with 5 simulations
        self.assertEqual(str(self.calib_manager.suite_id), suite_id)  # verify that resume still use same suite
        self.assertEqual(self.calib_manager.current_iteration.status, StatusPoint.done)

    def test_dummy_calibra_manager_ll_all(self):
        uniq_filename = str(datetime.datetime.now().date()) + '_' + str(datetime.datetime.now().time()).replace(':',
                                                                                                                '-')
        directory = os.path.join(CURRENT_DIRECTORY, "calibra_result", uniq_filename)
        self.calib_manager.run_calibration(directory=directory)
        try:
            self.calib_manager.run_calibration(directory=directory, ll_all=True)
        except:  # otherwise after generate ll_call_final.csv program exit(0)
            self.assertTrue(
                os.path.exists(os.path.join(directory, "test_dummy_calibration", "_plots", "ll_all_final.csv")))
