import json
import os
import unittest
import datetime
import pandas as pd

from idmtools.assets import AssetCollection
from idmtools.core import ItemType
from idmtools.core.platform_factory import Platform
from idmtools_models.python.json_python_task import JSONConfiguredPythonTask

from idmtools_calibra.algorithms.optim_tool import OptimTool
from idmtools_calibra.calib_manager import CalibManager
from idmtools_calibra.plotters.likelihood_plotter import LikelihoodPlotter
from idmtools_calibra.plotters.site_data_plotter import SiteDataPlotter
from idmtools_calibra.process_state import StatusPoint
from idmtools_calibra.rmse_site import RMSESite
import params


CURRENT_DIRECTORY = os.path.dirname(__file__)


class TestCalibraManager(unittest.TestCase):

    def setUp(self) -> None:
        def map_sample_to_model_input(simulation, sample):
            """
            This method maps the samples generated by the next point algorithm to the model inputs (via the simulation object).
            All parameters specified for dynamic calibration (above) that do not have a MapTo value must have associated mapping
                logic in this method.
            Args:
                simulation: idmtools simulation
                sample: The sample containing a values for all the params. e.g. {'Clinical Fever Threshold High':1, ... }

            Returns: A dictionary containing the tags that will be attached to the simulation
            """

            tags = {}
            from functools import partial
            for p in params.CALIBRATION_PARAMETERS:
                if "MapTo" not in p:
                    raise Exception(
                        "Calibration parameter dicts must include a MapTo (model param name) entry. Missing from parameter: %s"
                        % p["Name"]
                    )
                if p["Name"] not in sample:
                    print(
                        "Warning: %s not in sample, perhaps resuming previous iteration"
                        % p["Name"]
                    )
                    continue
                value = sample.pop(p["Name"])
                mapto_key = p["MapTo"]
                tags.update(simulation.task.set_parameter(mapto_key.replace("config:", ""), value))

            for name, value in sample.items():
                print("UNUSED PARAMETER:" + name)
            assert len(sample) == 0  # All params used
            return tags

        self.site = RMSESite(
            name='rmse_site',
            reference_sources={
                'production': os.path.join('..', '..', 'examples', 'solar', 'reference', 'production.csv')}
        )
        self.n_samples = 5
        self.max_iterations = 2
        self.calibra_name = 'test_dummy_calibration'
        self.optimtool = OptimTool(params.CALIBRATION_PARAMETERS, samples_per_iteration=self.n_samples)
        plotters = [LikelihoodPlotter(True), SiteDataPlotter(True)]
        assets = AssetCollection()
        assets.add_directory(os.path.join('..', '..', 'examples', 'solar', 'bin'), relative_path="bin")
        task = JSONConfiguredPythonTask(
            script_path=str(os.path.join('..', '..', 'examples', 'solar', 'bin', 'linear_model.py')),
            common_assets=assets,
            config_file_name='config.json')
        self.calib_manager = CalibManager(
            name=self.calibra_name,
            task=task,
            map_sample_to_model_input_fn=map_sample_to_model_input,
            sites=[self.site],
            next_point=self.optimtool,
            sim_runs_per_param_set=1,
            max_iterations=self.max_iterations,
            plotters=plotters)
        self.platform = Platform("SlurmStage")
        self.calib_manager.platform = self.platform
        self.case_name = self._testMethodName

        date = datetime.datetime.now()
        uniq_filename = str(date.date()) + '_' + str(date.time()).replace(':', '_')
        #uniq_filename = "2023-02-07_09_12_46.651237"
        self.directory = os.path.join(CURRENT_DIRECTORY, "calibra_result", uniq_filename)
        self.calib_manager.name = self.case_name
        self.calib_manager.run_calibration(directory=self.directory)

    def test_calibration_run(self):
        # Open the IterationState.json from iter0 and check values
        with open(f'{self.directory}/{self.calib_manager.name}/iter0/IterationState.json', 'r') as fp:
            it = json.load(fp)
            for sample in it['samples_for_this_iteration']:
                self.assertTrue(sample['linear-coefficient'] >= self.optimtool.params[0]['Min']
                                or sample['linear-coefficient'] <= self.optimtool.params[0]['Max'])
                self.assertTrue(sample['constant'] >= self.optimtool.params[1]['Min']
                                or sample['constant'] <= self.optimtool.params[1]['Max'])
            self.assertEqual(len(it['samples_for_this_iteration']), self.n_samples)
            self.assertEqual(it['status'], 'done')
            self.assertEqual(it['location'], "SlurmStage")
            self.assertTrue(self.site.get_analyzers()[0].__class__.__name__ in it['analyzers']['RMSEAnalyzer'])
            self.assertEqual(it['iteration'], 0)
            self.assertListEqual(it['results']['RMSEAnalyzer'], it['results']['total'])
            self.assertEqual(it['calibration_name'], self.calib_manager.name)
            self.assertEqual((it['next_point']['samples_per_iteration']), self.n_samples)
            self.assertEqual(it['next_point']['params'], self.optimtool.params)
            self.assertEqual(it['next_point']['state'],
                             {'Iteration': [0, 0], 'Parameter': ['linear-coefficient', 'constant'], 'Center': [50, 500],
                              'Min': [0, 0], 'Max': [400, 2000], 'Dynamic': [True, True]})

        # Verify iter1 directory exists
        self.assertTrue(os.path.exists(
            os.path.join(self.directory, self.calib_manager.name, f'iter{self.max_iterations - 1}')))
        # Verify CalibraManager.json content
        with open(os.path.join(os.path.join(self.directory, self.calib_manager.name, 'CalibManager.json')), 'r') as fp:
            cm = json.load(fp)
            self.assertEqual(cm['name'], self.calib_manager.name)
            self.assertEqual(cm['location'], "SlurmStage")
            self.assertEqual(cm['sites'], {'rmse_site': ['RMSEAnalyzer']})
            self.assertEqual(cm['param_names'], ['linear-coefficient', 'constant'])
            result_keys = ['sample', 'iteration', 'total', 'RMSEAnalyzer', 'linear-coefficient', 'constant']
            for key, value in cm['results'].items():
                self.assertEqual(len(value), self.n_samples * self.max_iterations)
                self.assertTrue(bool([x for x in result_keys if (x in key)]))

    def test_dummy_calibra_manager_resume(self):
        # Verify current iteration from setupClass:
        self.assertEqual(self.calib_manager.current_iteration.iteration, 1)
        self.assertEqual(self.calib_manager.all_results.shape[0],
                         self.n_samples * self.max_iterations)  # 2*(5sim/iter) iterations
        experiments = self.platform.get_children(self.calib_manager.suite_id, ItemType.SUITE)
        # Verify comps has 2 experiments created at this point
        self.assertEqual(len(experiments), 2)
        # Resume from iteration 0 commission step and stop
        self.calib_manager.run_calibration(directory=self.directory, resume=True, iteration=0, iter_step='commission',
                                           loop=False)
        self.assertEqual(self.calib_manager.current_iteration.iteration, 0)
        self.assertEqual(self.calib_manager.iteration, 0)
        self.assertEqual(self.calib_manager.all_results.shape[0],
                         self.n_samples)  # rerun only return first iteration with 5 simulations
        self.assertEqual(self.calib_manager.current_iteration.status, StatusPoint.done)
        experiments = self.platform.get_children(self.calib_manager.suite_id, ItemType.SUITE, force=True)
        # Verify comps has 3 (previous 2 + 1 new_ experiments created at this point
        self.assertEqual(len(experiments), 3)
        # Resume from iteration 0 commission step and run all the way through
        self.calib_manager.run_calibration(directory=self.directory, resume=True, iteration=0, iter_step='commission',
                                           loop=True)
        self.assertEqual(self.calib_manager.current_iteration.iteration, 1)
        self.assertEqual(self.calib_manager.iteration, 1)
        experiments = self.platform.get_children(self.calib_manager.suite_id, ItemType.SUITE, force=True)
        # Verify comps has 5 experiments (previous 3 + 3 new_ experiments created at this point
        self.assertEqual(len(experiments), 5)
        # Resume from iteration 1 analyze step and run all the way through
        self.calib_manager.run_calibration(directory=self.directory, resume=True, iteration=0, iter_step='analyze',
                                           loop=True)
        self.assertEqual(self.calib_manager.current_iteration.iteration, 1)
        experiments = self.platform.get_children(self.calib_manager.suite_id, ItemType.SUITE, force=True)
        # Verify comps has 6 experiments (previous 5 + 1 new_ experiment created at this point, since we only start from
        # iter1 for new commission
        self.assertEqual(len(experiments), 6)

    def test_dummy_calibra_manager_ll_all(self):
        # Note, we need to put in try/except block here. Otherwise after generate ll_call_final.csv program calls exit(0)
        # which will quit before assert
        try:
            self.calib_manager.run_calibration(directory=self.directory, ll_all=True)
        except SystemExit:
            self.assertTrue(
                os.path.exists(os.path.join(self.directory, self.calib_manager.name, "_plots", "ll_all_final.csv")))

            # Verify ll_all_final.csv and ll_all.csv are same
            df1 = pd.read_csv(os.path.join(self.directory, self.calib_manager.name, "_plots", "ll_all_final.csv"))
            df2 = pd.read_csv(os.path.join(self.directory, self.calib_manager.name, "_plots", "LL_all.csv"))
            changed = df1.compare(df2)
            self.assertTrue(changed.empty)

