# This workflows will install idmtools_calibra from setup-dev then run tests with curl command
#
#curl command from your cmd:
# curl -XPOST -u "username:githubPAT" -H "Accept: application/vnd.github.everest-preview+json" \
# -H "Content-Type: application/json" \
# --data "{\"event_type\": \"run_setup_dev_test\"}" \
#  https://api.github.com/repos/InstituteforDiseaseModeling/idmtools_calibra/dispatches
#
# Note, this test will checkout 'dev' branch
name: "run_bootstrap_and_test"
on: [push, pull_request]
#  repository_dispatch:
#    types: [run_setup_dev_test]
#  workflow_dispatch:
#  pull_request:
#   types: [opened, edited, reopened]

jobs:
  install-setup-dev-run-all-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]
    env:
      PYPI_STAGING_USERNAME: ${{ secrets.PYPI_STAGING_USERNAME }}
      PYPI_STAGING_PASSWORD: ${{ secrets.PYPI_STAGING_PASSWORD }}
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2
        with:
          ref: dev
      - name: Set up Python ${{ matrix.python-version  }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Python dependencies
        run: |
          sudo apt-get update
          sudo apt-get install make
          pip install black flake8
          python -m pip install --upgrade pip
      - name: Run bootstrap
        run: |
          python .dev_scripts/bootstrap.py
      - name: install dependencies
        run: |
          pip install -r requirements.txt
          path: examples/emod_sir/OutputOption1
      - name: login to comps2
        run: |
          python .dev_scripts/create_auth_token_args.py --username "${{ secrets.COMPS_USER }}"
        env:
            COMPS_PASS: ${ { secrets.COMPS_PASSWORD } }
      - name: run idmtools_calibra integration tests
        run: |
          cd tests/integration
          py.test -v --durations=3 --junitxml=test_results.xml
      - name: Upload idmtools_calibra test results
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: idmtools_calibra_test_results
          path: tests/integration/test_results.xml